# Generated by Django 3.1.5 on 2021-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event name')),
                ('description', models.TextField(verbose_name='Description')),
                ('localization_name', models.CharField(max_length=255, verbose_name='Localization name')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('date', models.DateTimeField(verbose_name='Event date')),
                ('artists', models.ManyToManyField(to='artists.Artist', verbose_name='Artists')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
