# Generated by Django 3.1.5 on 2021-01-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artist',
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(to='artists.Artist', verbose_name='Artists'),
        ),
    ]
