
version: "3.9"

services:
  db:
    image: kartoza/postgis:9.6-2.4
    environment:
      - POSTGRES_DB=music-events
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/musicevents
    ports:
      - "8000:8000"
    depends_on:
      - db