# Generated by Django 3.1.5 on 2021-01-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Artist name')),
                ('genre', models.CharField(max_length=255, verbose_name='Music genre')),
            ],
        ),
    ]
